const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.scrollto,
		C3.Behaviors.Platform,
		C3.Plugins.Keyboard,
		C3.Behaviors.solid,
		C3.Plugins.Mouse,
		C3.Plugins.TiledBg,
		C3.Plugins.Text,
		C3.Behaviors.jumpthru,
		C3.Behaviors.Bullet,
		C3.Plugins.Audio,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.JavaScriptInEvents.FolhaDoTutorial_Event2_Act1,
		C3.JavaScriptInEvents.FolhaDoTutorial_Event3_Act1,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.System.Acts.GoToLayout,
		C3.JavaScriptInEvents.PrimeiraFolhaDoBoss_Event1_Act1,
		C3.JavaScriptInEvents.PrimeiraFolhaDoBoss_Event2_Act1,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.Play,
		C3.JavaScriptInEvents.FolhaSegundaFase_Event2_Act1,
		C3.JavaScriptInEvents.FolhaSegundaFase_Event3_Act1,
		C3.Plugins.Mouse.Cnds.OnClick
	];
};
self.C3_JsPropNameTable = [
	{CentrarEm: 0},
	{Plataforma: 0},
	{personagem: 0},
	{Teclado: 0},
	{Sólido: 0},
	{Sprite4: 0},
	{Mouse: 0},
	{PlanoTutorial: 0},
	{Sprite14: 0},
	{Titulo: 0},
	{IrBoss: 0},
	{SetaDireita: 0},
	{setaEsquerda: 0},
	{setaCima: 0},
	{atirar: 0},
	{puxarArma: 0},
	{Sprite2: 0},
	{Sprite6: 0},
	{Sprite16: 0},
	{Sprite17: 0},
	{Sprite18: 0},
	{Sprite19: 0},
	{Sprite8: 0},
	{PularAtravés: 0},
	{Sprite7: 0},
	{PlanoPrimeiraFase: 0},
	{InimigoBoss: 0},
	{PlanoDeFundoEmBlocos: 0},
	{Sprite5: 0},
	{PlanoDeFundoEmBlocos2: 0},
	{Sprite9: 0},
	{Sprite10: 0},
	{Sprite11: 0},
	{Projétil: 0},
	{tiro: 0},
	{barradevida: 0},
	{barradevidaper: 0},
	{tiroBoss: 0},
	{Áudio: 0},
	{PlanoDeFundoEmBlocos3: 0},
	{Sprite3: 0},
	{InimigoBoss2: 0},
	{tiroBoss2: 0},
	{barradevida2: 0},
	{barradevidaper2: 0},
	{TelaDeVitóriaFuturistaComBotões: 0},
	{continuar: 0},
	{Sprite13: 0},
	{Sprite15: 0},
	{Sprite20: 0},
	{Sprite21: 0},
	{Sprite22: 0}
];

self.InstanceType = {
	personagem: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	PlanoTutorial: class extends self.ITiledBackgroundInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	Titulo: class extends self.ITextInstance {},
	IrBoss: class extends self.ITextInstance {},
	SetaDireita: class extends self.ITextInstance {},
	setaEsquerda: class extends self.ITextInstance {},
	setaCima: class extends self.ITextInstance {},
	atirar: class extends self.ITextInstance {},
	puxarArma: class extends self.ITextInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	Sprite17: class extends self.ISpriteInstance {},
	Sprite18: class extends self.ISpriteInstance {},
	Sprite19: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	PlanoPrimeiraFase: class extends self.ITiledBackgroundInstance {},
	InimigoBoss: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos: class extends self.ITiledBackgroundInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos2: class extends self.ITiledBackgroundInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	tiro: class extends self.ISpriteInstance {},
	barradevida: class extends self.ISpriteInstance {},
	barradevidaper: class extends self.ISpriteInstance {},
	tiroBoss: class extends self.ISpriteInstance {},
	Áudio: class extends self.IInstance {},
	PlanoDeFundoEmBlocos3: class extends self.ITiledBackgroundInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	InimigoBoss2: class extends self.ISpriteInstance {},
	tiroBoss2: class extends self.ISpriteInstance {},
	barradevida2: class extends self.ISpriteInstance {},
	barradevidaper2: class extends self.ISpriteInstance {},
	TelaDeVitóriaFuturistaComBotões: class extends self.ISpriteInstance {},
	continuar: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	Sprite20: class extends self.ISpriteInstance {},
	Sprite21: class extends self.ISpriteInstance {},
	Sprite22: class extends self.ISpriteInstance {}
}